version: '3.8'

services:
  # --- 1. Middleware ---
  rabbit-server:
    image: rabbitmq:3.13-management
    container_name: rabbit-server
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shibasito-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- 2. Base de Datos del Banco (BD1) ---
  db-banco:
    image: postgres:16
    container_name: db-banco
    environment:
      POSTGRES_USER: shibasito_user
      POSTGRES_PASSWORD: shibasito_password
      POSTGRES_DB: bd1_banco
    ports:
      - "5432:5432"
    volumes:
      - ./sql-scripts/init-banco.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shibasito-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shibasito_user -d bd1_banco"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- 3. Base de Datos de RENIEC (BD2) - (NUEVO) ---
  db-reniec:
    image: mysql:8.0
    container_name: db-reniec
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Clave de root
      MYSQL_DATABASE: bd2_reniec
      MYSQL_USER: shibasito_user
      MYSQL_PASSWORD: shibasito_password
    ports:
      - "3306:3306" # Expone el puerto de MySQL a tu PC
    volumes:
      # Carga el script SQL al iniciar (modo efímero)
      - ./sql-scripts/init-reniec.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shibasito-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "shibasito_user", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- 4. Servicio LP1 BANCO (Java) ---
  lp1-banco-servicio:
    build: ./lp1-banco-java
    container_name: lp1-banco-servicio
    networks:
      - shibasito-net
    ports:
      - "8080:8080"
    depends_on:
      rabbit-server:
        condition: service_healthy
      db-banco:
        condition: service_healthy
    restart: on-failure

  # --- 5. Servicio LP2 RENIEC (Node.js) - (NUEVO) ---
  lp2-reniec-servicio:
    build: ./lp2-reniec-nodejs  # Construye desde la nueva carpeta
    container_name: lp2-reniec-servicio
    networks:
      - shibasito-net
    environment:
      # Pasamos las URLs de los otros servicios (los nombres deben coincidir)
      - RABBITMQ_URL=amqp://guest:guest@rabbit-server:5672
      - MYSQL_HOST=db-reniec
      - MYSQL_USER=shibasito_user
      - MYSQL_PASSWORD=shibasito_password
      - MYSQL_DATABASE=bd2_reniec
    depends_on:
      rabbit-server:
        condition: service_healthy # Espera a que RabbitMQ esté listo
      db-reniec:
        condition: service_healthy # Espera a que la BD Reniec esté lista
    restart: on-failure

# --- Red Personalizada ---
networks:
  shibasito-net:
    driver: bridge